// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4f-1qeSFumqlMPzK8z-kYhgLwxo1--JU',
    appId: '1:89056374320:android:9de759dd2f86a9607447f5',
    messagingSenderId: '89056374320',
    projectId: 'flutter002-1d47e',
    databaseURL: 'https://flutter002-1d47e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter002-1d47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7a3_Umvr_VaVAgXMTtcdtDOgbuHLcvzk',
    appId: '1:89056374320:ios:052111518f26ec387447f5',
    messagingSenderId: '89056374320',
    projectId: 'flutter002-1d47e',
    databaseURL: 'https://flutter002-1d47e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter002-1d47e.firebasestorage.app',
    iosBundleId: 'com.cmmapps.globalchat',
  );
}
