name: Build and Distribute APK to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: List APK directory
        run: ls -la build/app/outputs/flutter-apk/

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Distribute via Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.TOKEN }}
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "APPID" \
            --release-notes "Build from commit ${{ github.sha }}" \
            --testers "email1@example.com,email2@example.com"

      - name: Upload APK to GitHub Actions Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-release.apk
